#!/usr/local/bin/bash -e

LABEL=$(echo $1 | sed 's|iso9660/||')
DEVICE=$(/usr/local/sbin/blkid -t LABEL="$LABEL" /dev/cd* | cut -d ":" -f 1)

DISCNAME=UNKNOWN
OUTPUTDIR=/mnt/freerip
LOGDIR=${OUTPUTDIR}/logs

# arg parsing
CDEV="$1"
